// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sptwspntkjdvhcpklarp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNwdHdzcG50a2pkdmhjcGtsYXJwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4NTY4ODAsImV4cCI6MjA1OTQzMjg4MH0.cgbna3vffvxiYDyrncJplTf3s7XPWpjzR_odl0Td2Os";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);